version: "3"
services:
  client:
    build:
      context: ./web-client
      dockerfile: ./dev.Dockerfile
    container_name: client
    tty: true
    command: npm run serve
    environment:
      - VUE_APP_API_URL=http://api:3030
    volumes:
      - ./web-client/src:/app/src
    ports:
      - 9090:8080
    depends_on:
      - api
  api:
    build: ./api
    container_name: api
    command: npm run serve
    volumes:
      - ./api/src:/app/src
      - ./api/public:/app/public
      - ./api/config:/app/config
    environment:
      - NODE_ENV=docker
    ports:
      - 33333:33333/udp
  mongo:
    image: mongo:3.6
    container_name: mongo
    volumes:
       - mongodb-data:/data/db
    ports:
      - 27017:27017
    logging:
      driver: none

volumes:
  mongodb-data: